version: '3.8'

services:
  kafka:
    image: apache/kafka:3.7.1
    container_name: xKafka
    ports:
      - "9092:9092"
    restart: always

  timescaleDb:
    image: timescale/timescaledb:latest-pg12
    container_name: exness-timescaleDb
    ports:
      - "5433:5432" 
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=exchange
    volumes:
      - timescale-data:/var/lib/postgresql/data
    restart: always
  
  redis:
    image: redis:latest
    container_name: exness_redis
    ports:
      - "6379:6379"
    restart: always

  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
  timescale-data:
